Added user event callbacks
nattog/passthrough pull request #2
Opened 2020-06-28 16:38 UTC by frederickk

I made some tweaks to this for my [Stjörnuíþrótt:](https://github.com/frederickk/stjoernuithrott) drone to allow for user event handling in addition to how passthrough handles midi. I thought it might be of interest to others.

2020-06-28 21:00 UTC, nattog requested changes
Thanks for this, certainly a nice feature to add! I'll try it out on the hardware tomorrow, just one small thing at a first glance.

2020-06-28 21:00 UTC, nattog commented on example-event.lua
> +function midi_output_event(data)
```suggestion
function midi_interface_event(data)
```

2020-06-28 21:00 UTC, nattog commented on example-event.lua
> +    Passthrough.user_output_event = midi_output_event
```suggestion
    Passthrough.user_interface_event = midi_interface_event
```

2020-06-28 21:46 UTC, frederickk commented on example-event.lua
> +    Passthrough.user_output_event = midi_output_event
Good catch! Left that in there from my debugging.

2020-06-29 19:05 UTC, frederickk commented
I amended with PR with the changes requested.

2020-06-29 21:07 UTC, nattog approved these changes
Works very nicely, thank you!

2020-06-29 21:08 UTC, merged